version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    user: postgres
    expose:
      - 5432
      - 6432
    ports:
      - "6432:5432"
    env_file:
      - ./.env.dev
    networks:
      - app-network 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "fortris"]
      interval: 10s
      timeout: 5s
      retries: 5 

  api:
    build: './api'
    ports:
      - "6667:8080"
    restart: "always"
    env_file:
      - ./.env.dev
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network  

  ranking:
    build: './ranking'
    ports:
      - "8081:8080"
    env_file:
      - ./.env.dev
    networks:
      - app-network  
  
  pricing:
    build: './pricing'
    ports:
      - "8082:8080"
    env_file:
      - ./.env.dev
    networks:
      - app-network  

volumes:
  postgres_data:

networks:
  app-network:
