version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    user: postgres
    expose:
      - 5432
      - 6432
    ports:
      - "6432:5432"
    env_file:
      - ./.env.dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "fortris"] 
      interval: 10s
      timeout: 5s
      retries: 5 

  api:
    build: './api'
    container_name: api
    ports:
      - "6667:8080"
    restart: "always"
    env_file:
      - ./.env.dev
    depends_on:
      postgres:
        condition: service_healthy

  ranking:
    build: './ranking'
    container_name: ranking
    ports:
      - "8081:8081"
    env_file:
      - ./.env.dev
  
  pricing:
    build: './pricing'
    container_name: pricing
    ports:
      - "8082:8082"
    env_file:
      - ./.env.dev

# volumes:
#   postgres_data:
